# Intro To NumPy
https://numpy.org/

https://numpy.org/doc/

![](../images/numpy.png)

![](../images/numpy-anatomy-of-an-array.png)

### Key terms:

* **Array** - A list of numbers, can be multi-dimensional.

* **Scalar** - A single number (e.g. 7).

* **Vector** - A list of numbers with 1-dimension (e.g. np.array([1, 2, 3])).

* **Matrix** - A (usually) multi-dimensional list of numbers (e.g. np.array([[1, 2, 3], [4, 5, 6]])).


# 0. Importing NumPy
To get started using NumPy, the first step is to import it.

The most common way (and method you should use) is to import NumPy as the abbreviation np.

If you see the letters np used anywhere in machine learning or data science, it's probably referring to the NumPy library.

In [220]:
import numpy as np

# Check the version
print(np.__version__)

1.26.0


# Data Types and Attributes 

In [221]:
# NumPY's main datatype is ndarray
a1 = np.array([1,2,3])
a1 


array([1, 2, 3])

In [222]:
type(a1)

numpy.ndarray

In [223]:
a2 = np.array([[1, 2.0, 3.3], 
              [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [224]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [225]:
# Check the shape of each array's with the .shape attribute 

In [226]:
a1.shape

(3,)

In [227]:
a2.shape

(2, 3)

In [228]:
a3.shape

(2, 3, 3)

In [229]:
# Let's check the dimentions with .ndim attribute

In [230]:
a1.ndim,  a2.ndim,  a3.ndim 

(1, 2, 3)

In [231]:
# Let's check the data type with the dtype attribute

a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [232]:
# lets check how many total elements are in each erray with the size attribute
a1.size, a2.size, a3.size


(3, 6, 18)

In [233]:
# All of theese are an universal nupy data type called ndarray
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [234]:
# Create a DataFrame from a NumPy array 
import pandas as pd
df= pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

# 2. Creating arryas 

In [235]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [236]:
sample_array.dtype

dtype('int64')

In [237]:
# create an arrya with ones 
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [238]:
ones.dtype

dtype('float64')

In [239]:
type(ones)

numpy.ndarray

In [240]:
# create an array with zeors 
zeors = np.zeros((2,3))
zeors

array([[0., 0., 0.],
       [0., 0., 0.]])

In [241]:
zeors.dtype

dtype('float64')

In [242]:
type(zeors)

numpy.ndarray

In [243]:
# create an array with ranges between 0 to 10 , and a step of 2 with the arrange() function 
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [244]:
# create a random array containing numbers between 0 and 10,  with the randint() function 
random_array = np.random.randint(0,10, size=(3,5))
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [245]:
random_array.size

15

In [246]:
random_array.shape

(3, 5)

In [247]:
type(random_array)

numpy.ndarray

In [248]:
# lets use the random.random() function 
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.79915856, 0.46147936, 0.78052918],
       [0.11827443, 0.63992102, 0.14335329],
       [0.94466892, 0.52184832, 0.41466194],
       [0.26455561, 0.77423369, 0.45615033],
       [0.56843395, 0.0187898 , 0.6176355 ]])

In [249]:
random_array_2.shape

(5, 3)

In [250]:
# lets use the random.rand() function 
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.61209572, 0.616934  , 0.94374808],
       [0.6818203 , 0.3595079 , 0.43703195],
       [0.6976312 , 0.06022547, 0.66676672],
       [0.67063787, 0.21038256, 0.1289263 ],
       [0.31542835, 0.36371077, 0.57019677]])

In [251]:
# Pseudo-random numbers
np.random.seed(seed=99999)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [252]:
# A random seed will set random numbers that can be created with the same seed every single time
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [253]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

# 3. Viewing arrays and matrices
#### numpy.unique documentation: 
https://numpy.org/doc/stable/reference/generated/numpy.unique.html



In [254]:
np.unique(random_array_4)

array([0, 1, 3, 4, 5, 6, 8, 9])

In [255]:
a1

array([1, 2, 3])

In [256]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [257]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [258]:
a1[0]

1

In [259]:
a2.shape

(2, 3)

In [260]:
a2[0]

array([1. , 2. , 3.3])

In [261]:
a3.shape

(2, 3, 3)

In [262]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [263]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [264]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [265]:
a2[1]

array([4. , 5. , 6.5])

In [266]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [267]:
a3.shape

(2, 3, 3)

In [268]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [269]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [270]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [271]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :1]

array([[[[3],
         [5],
         [9],
         [3]],

        [[1],
         [7],
         [7],
         [3]],

        [[4],
         [9],
         [2],
         [9]]],


       [[[3],
         [7],
         [6],
         [7]],

        [[9],
         [6],
         [6],
         [9]],

        [[7],
         [8],
         [3],
         [7]]]])

# 4. Manipulating & comparing arrays

* ###  Arithmetic
    * +, -, *, /, //, **, %
    * np.exp()
    * np.log()
    * Dot product - np.dot()
    * Broadcasting

In [272]:
a1 

array([1, 2, 3])

In [273]:
ones = np.ones(3)
ones 

array([1., 1., 1.])

In [274]:
# Add two arrays
a1 + ones

array([2., 3., 4.])

In [275]:
# Subtract two arrays
a1 - ones

array([0., 1., 2.])

In [276]:
# Multiply two arrays
a1 * ones

array([1., 2., 3.])

In [277]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [278]:
# Multiply two arrays
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [279]:
a1.shape, a2.shape

((3,), (2, 3))

In [280]:
# This will error as the arrays have a different number of dimensions (2, 3) vs. (2, 3, 3) 
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
a1 / ones

In [ ]:
a2 / a1

In [ ]:
# Floor division removes the decimals (rounds down)
a2 // a1

In [ ]:
a2

In [ ]:
# Square
a2 ** 2

In [ ]:
# NumPY square function 
np.square(a2)

In [ ]:
a1 + ones

In [ ]:
np.add(a1, ones)

In [ ]:
a1 / 2

In [ ]:
# modulo (remainder
a1 % 2

In [ ]:
# exponent function 
np.exp(a1)

In [ ]:
# log function
np.log(a1)

* ### Aggregation : bringin together, peforming the same operation on a number of things  
    * np.sum() - faster than Python's .sum() for NumPy arrays
    * np.mean()
    * np.std()
    * np.var()
    * np.min()
    * np.max()
    * np.argmin() - find index of minimum value
    * np.argmax() - find index of maximum value
    * These work on all ndarray's
    * a4.min(axis=0) -- you can use axis as well

#### **Tip**: Use NumPy's np.sum() on NumPy arrays and Python's sum() on Python lists.

In [ ]:
sum(listy_list)

In [ ]:
sum(a1)

In [ ]:
np.sum(a1)

#### Notice np.sum() is faster on the Numpy array (numpy.ndarray) than Python's sum().

In [ ]:
# Crating a massive Numpy array 
massive_array = np.random.random(100000)

In [ ]:
massive_array [:10]

In [ ]:
%timeit sum(massive_array) # Python sum()
%timeit np.sum(massive_array) # NumPy np.sum()

In [ ]:
a2 

In [ ]:
np.mean(a2)

In [ ]:
np.max(a2)

In [ ]:
np.min(a2)

**Standard** deviation and **variance** are measures of 'spread' of data.

The higher standard deviation and the higher variance of data, the more spread out the values are.

The lower standard deviation and lower variance, the less spread out the values are.









What's mean?

Mean is the same as average. You can find the average of a set of numbers by adding them up and dividing them by how many there are.

What's standard deviation?

Standard deviation is a measure of how spread out numbers are.

What's variance?

The variance is the averaged squared differences of the mean.

To work it out, you:

Work out the mean
For each number, subtract the mean and square the result
Find the average of the squared differences

In [ ]:
# Standard deviation = a measure of how spread out a group of numbers is from the mean
# https://www.mathsisfun.com/data/standard-deviation.html

np.std(a2)

In [ ]:
# Variance = measure of the average degree to which each number is different to the mean
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers

np.var(a2)

In [ ]:
# Standard deviation = squareroot of variance
np.sqrt(np.var(a2))

In [ ]:
# Demo of std and var
high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([2, 4, 6, 8, 10])

In [ ]:
np.var(high_var_array), np.var(low_var_array)

In [ ]:
np.std(high_var_array), np.var(low_var_array)

In [ ]:
np.mean(high_var_array), np.mean(low_var_array)

In [ ]:
%matplotlib inline 
import matplotlib.pyplot as plt 
plt.hist(high_var_array)
plt.show()

In [ ]:
%matplotlib inline 
import matplotlib.pyplot as plt 
plt.hist(low_var_array)
plt.show()

* ### Reshaping
    * np.reshape()

In [ ]:
a2

In [ ]:
a2.shape

In [ ]:
a2 * a3

In [ ]:
a2_reshape = a2.reshape(2, 3, 1)
a2_reshape

In [ ]:
a3

In [ ]:
a2_reshape * a3

* ### Transposing
A tranpose reverses the order of the axes.
For example, an array with shape (2, 3) becomes (3, 2)

In [ ]:
a2

In [ ]:
a2.shape

In [ ]:
# Transpose = switches the axis' , a2.transpose()
a2.T

In [ ]:
a2.T.shape

In [ ]:
a3

In [ ]:
a3.shape

In [ ]:
a3.T

In [ ]:
a3.T.shape

# Dot product
The main two rules for dot product to remember are:

1. The inner dimensions must match:
    * (3, 2) @ (3, 2) won't work
    * (2, 3) @ (3, 2) will work
    * (3, 2) @ (2, 3) will work
2. The resulting matrix has the shape of the outer dimensions:
    * (2, 3) @ (3, 2) -> (2, 2)
    * (3, 2) @ (2, 3) -> (3, 3)
  
**Note:** In NumPy, np.dot() and @ can be used to acheive the same result for 1-2 dimension arrays. However, their behaviour begins to differ at arrays with 3+ dimensions.

**Matrix Multiplicatin Explained:** https://www.mathsisfun.com/algebra/matrix-multiplying.html
  * http://matrixmultiplication.xyz/

![](images/dot-vs-element.png)

![](images/dot-product.png)

In [281]:
# randint function takes randoms integers from low to high
np.random.seed(0)
mat1 = np.random.randint(10, size=(5, 3))
mat2 = np.random.randint(10, size=(5, 3))                   

In [282]:
mat1.shape, mat2.shape

((5, 3), (5, 3))

In [283]:
mat1 

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [284]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [285]:
# Element-wise multiplication(Hadamard product)    # np.multiply()
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [287]:
# Dot Product
# np.dot()

np.dot(mat1, mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [288]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [289]:
# Transpose mat1
mat1 = mat1.T

In [290]:
mat1.shape

(3, 5)

In [291]:
mat1.shape, mat2.shape

((3, 5), (5, 3))

In [292]:
mat3 = np.dot(mat1, mat2)
mat3

array([[121, 114,  77],
       [153, 108,  80],
       [135,  69,  84]])

In [293]:
mat3.shape

(3, 3)

# Dot product example (nut butter sales)

In [375]:
np.random.seed(0)
sales_amounts = np.random.randint(20, size=(5,3))

sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [376]:
# Create weekly_sales DataFrame
weekly_sales = pd.DataFrame(sales_amounts, 
                            index = ["Mon", "Tues", "Wed", "Thurs", "Fri"], 
                            columns = ["Almond butter", "Peanut butter", "Cashew butter"]) 
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [377]:
# Create prices array 
price = np.array([10, 8, 12])

price

array([10,  8, 12])

In [378]:
price.shape

(3,)

In [379]:
#Create butter_prices DataFrame
butter_prices = pd.DataFrame(price.reshape(1,3),
                             index = ["Price"], 
                             columns = ["Almond butter", "Peanut butter", "Cashew butter"])
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [380]:
sales_amounts.shape

(5, 3)

In [381]:
total_sales = price.dot(sales_amounts)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [382]:
# Shapes arent aligned, lets transpose sales_amounts
total_sales = price.dot(sales_amounts.T)

total_sales

array([240, 138, 458, 232, 142])

In [385]:
# butter prices 
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [384]:
# weekly sales 
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [386]:
# check shape of both sales
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [387]:
# if we trnaspose one 
weekly_sales.T.shape

(3, 5)

In [388]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales.shape

(1, 5)

In [391]:
daily_sales

Mon  Tues  Wed  Thurs  Fri
Price  240   138  458    232  142

In [390]:
daily_sales.T

Price
Mon      240
Tues     138
Wed      458
Thurs    232
Fri      142

In [393]:
# add total price column 
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total ($)
Mon               12             15              0        240
Tues               3              3              7        138
Wed                9             19             18        458
Thurs              4              6             12        232
Fri                1              6              7        142

* ### Comparison operators

  Finding out if one array is larger, smaller or equal to another.
  
    * '>'
    * <
    * <=`
    * '>='
    * x != 3
    * x == 3
    * np.sum(x > 3)
      


In [394]:
a1

array([1, 2, 3])

In [395]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [396]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [397]:
a1 >= a2

array([[ True,  True, False],
       [False, False, False]])

In [398]:
a1 > 5

array([False, False, False])

In [399]:
a1 == a1

array([ True,  True,  True])

In [400]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

# 5. Sorting arrays

* [np.sort()](https://numpy.org/doc/stable/reference/generated/numpy.sort.html) - sort values in a specified dimension of an array.
* [np.argsort()](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html) - return the indices to sort the array on a given axis.
* [np.argmax()](https://numpy.org/doc/stable/reference/generated/numpy.argmax.html)- return the index/indicies which gives the highest value(s) along an axis.
* [np.argmin()](https://numpy.org/doc/stable/reference/generated/numpy.argmin.html)- return the index/indices which gives the lowest value(s) along an axis.

In [401]:
random_array = np.random.randint(10, size=(3, 5))
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [402]:
random_array.shape

(3, 5)

In [403]:
# sort 
np.sort(random_array)

array([[1, 5, 7, 8, 9],
       [0, 3, 4, 8, 9],
       [0, 2, 3, 3, 5]])

In [405]:
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [404]:
# argsort
np.argsort(random_array)

array([[2, 3, 0, 1, 4],
       [4, 3, 2, 0, 1],
       [2, 3, 0, 4, 1]])

In [406]:
a1

array([1, 2, 3])

In [407]:
np.argsort(a1)

array([0, 1, 2])

In [409]:
# argmax()
np.argmax(random_array, axis=0)

array([1, 1, 1, 0, 0])

In [410]:
np.argmax(random_array, axis=1)

array([4, 1, 1])

In [411]:
# argmin() 
np.argmin(random_array, axis=0)

array([2, 2, 2, 2, 1])

In [413]:
np.argmin(random_array, axis=1)

array([2, 4, 2])

# 6. Practical Example - NumPy in Action!!!!

<img src="images/numpy-images/panda.png"/>

In [434]:
# Turn an image into a NumPy array
from matplotlib.image import imread

panda = imread("images/numpy-images/panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [435]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [436]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

![](images/numpy-images/car.png)

In [441]:
car = imread("images/numpy-images/car.png")
print(type(car))

<class 'numpy.ndarray'>


In [442]:
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352

![](images/numpy-images/dog.png)

In [446]:
dog = imread("images/numpy-images/dog.png")
print(type(dog))


<class 'numpy.ndarray'>


In [447]:
dog

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.686274